In [40]:
import numpy as np

In [41]:
# Create an empty array with 2 elements
np.empty(4) 

array([2.12199579e-314, 1.26683149e-311, 3.59679790e-321, 3.79442416e-321])

In [4]:
np.arange(4)

array([0, 1, 2, 3])

In [5]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [6]:
np.linspace(0, 10, num=5) # Is ka mtlb 0 se 10 tak 5 numbers

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [7]:
x = np.ones(3, dtype=np.int64)
x

array([1, 1, 1], dtype=int64)

In [8]:
x = np.zeros(2, dtype=np.int64)
x

array([0, 0], dtype=int64)

# Adding, removing, and sorting elements

In [9]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr.sort()
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [11]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

In [13]:
np.concatenate((x, y), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# How do you know the shape and size of an array?

In [14]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.ndim

3

In [15]:
array_example.shape

(3, 2, 4)

In [16]:
array_example.size

24

In [17]:
a = np.arange(7)
print(a)

[0 1 2 3 4 5 6]


In [18]:
b = a.reshape(1,1, 7)
print(b)

[[[0 1 2 3 4 5 6]]]


In [19]:
np.reshape(a, newshape=(1, 7), order='C')

array([[0, 1, 2, 3, 4, 5, 6]])

In [20]:
np.ndim

<function ndim at 0x00000255A770F930>

# How to convert a 1D array into a 2D array (how to add a new axis to an array)

In [21]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [22]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [23]:
row_vector = a[: ,np.newaxis]
row_vector.shape

(6, 1)

In [24]:
z = np.array([1, 2, 3, 4, 5, 6])
z.shape

(6,)

In [25]:
b = np.expand_dims(z, axis=0)
b.shape

(1, 6)

# Indexing & Slicing

In [26]:
data = np.array([1, 2, 3,4,5])

In [27]:
data[:3]

array([1, 2, 3])

In [28]:
y = np.array([[1 , 2, 3, 4],
               [5, 6, 7, 8], 
               [9, 10, 11, 12]])

In [29]:
len(y)

3

In [30]:
y.shape

(3, 4)

In [31]:
y.size

12

In [32]:
y.ndim

2

In [33]:
print(a[a < 5])

[1 2 3 4]


In [34]:
five_up = (a >= 5)
print(a[five_up])

[5 6]


In [35]:
divisible_by_2 = a[a%3==0]
print(divisible_by_2)

[3 6]


In [36]:
c = a[(a > 2) & (a < 11)]
print(c)

[3 4 5 6]


In [46]:
u = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [47]:
b = np.nonzero(a < 5)
print(b)

(array([0, 1, 2, 3], dtype=int64),)


In [51]:
not_there = np.nonzero(a == 32)
print(not_there)


(array([], dtype=int64),)


In [52]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
               [4, 4]])

In [56]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [58]:
x = np.arange(1, 25) .reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [61]:
np.vsplit(y, 3)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [62]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [63]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [65]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [66]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [67]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [70]:
data * data

array([1, 4])